name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-file:
          - tests/basic.tftest.hcl
          - tests/backup.tftest.hcl
          - tests/advanced.tftest.hcl
          - tests/validations.tftest.hcl
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-oidc/providers/github-oidc
          service_account: github-oidc@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - run: terraform fmt -check

      - run: terraform init

      - run: terraform test -filter ${{ matrix['test-file'] }}
        env:
          GOOGLE_PROJECT: ${{ vars.GOOGLE_PROJECT }}
          GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}
